name: Deploy Laravel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 3.27.140.44
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/Laravel-Deployment
            
            # Force update code
            git fetch --all
            git reset --hard origin/main
            
            # Install dependencies
            composer install --no-dev --optimize-autoloader
            
            # Clear and rebuild Laravel cache
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # CRITICAL: Reset permissions so Nginx can write to logs/cache
            sudo chown -R ec2-user:nginx .
            sudo chmod -R 775 storage bootstrap/cache
            
            # Restart services
            sudo systemctl restart php-fpm
            sudo systemctl restart nginx
